### ISSUE TITLE
make failes

### ISSUE THREAD

**Issue by stilsch** [ahknight/crc32c#2]
Hello,
I've no idea if i should use some special parameters here - just typed "make" in the cloned folder..
Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-43-generic x86_64)

g++ -O3 -DNDEBUG -msse4.2 -I. -Wall -Wextra -Wno-sign-compare   -c -o test/crc32c_test.o test/crc32c_test.cc
test/crc32c_test.cc: In member function ‘virtual void CRC32C_CPUDetection::run()’:
test/crc32c_test.cc:15:14: warning: variable ‘crc’ set but not used [-Wunused-but-set-variable]
     uint32_t crc = crc32c(crc32cInit(), NULL, 0);
              ^
g++ -O3 -DNDEBUG -msse4.2 -I. -Wall -Wextra -Wno-sign-compare   -c -o test/stupidunit.o test/stupidunit.cc
g++ -O3 -DNDEBUG -msse4.2 -I. -Wall -Wextra -Wno-sign-compare   -c -o logging/crc32c_tables.o logging/crc32c_tables
.cc
g++ -O3 -DNDEBUG -msse4.2 -I. -Wall -Wextra -Wno-sign-compare   -c -o logging/crc32c.o logging/crc32c.cc
c++ -o crc32c_test test/crc32c_test.o test/stupidunit.o logging/crc32c_tables.o logging/crc32c.o
g++ -O3 -DNDEBUG -msse4.2 -I. -Wall -Wextra -Wno-sign-compare   -c -o bench/crc32c_bench.o bench/crc32c_bench.cc
c++ -o crc32c_bench bench/crc32c_bench.o logging/crc32c_tables.o logging/crc32c.o
cc -O3 -DNDEBUG -msse4.2 -I. -Wall -Wextra -Wno-sign-compare   -c -o main.o main.c
main.c: In function ‘main’:
main.c:21:15: warning: unused parameter ‘argc’ [-Wunused-parameter]
 int main (int argc, const char \* argv[])
               ^
main.c:21:34: warning: unused parameter ‘argv’ [-Wunused-parameter]
 int main (int argc, const char \* argv[])
                                  ^
cc -O3 -DNDEBUG -msse4.2 -I. -Wall -Wextra -Wno-sign-compare   -c -o crc32c/crc32c.o crc32c/crc32c.c
crc32c/crc32c.c: In function ‘crc32cSlicingBy4’:
crc32c/crc32c.c:84:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (size_t li = 0; li < initial_bytes; li++) {
     ^
crc32c/crc32c.c:84:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
crc32c/crc32c.c:92:17: error: redefinition of ‘li’
     for (size_t li = 0; li < running_length/4; li++) {
                 ^
crc32c/crc32c.c:84:17: note: previous definition of ‘li’ was here
     for (size_t li = 0; li < initial_bytes; li++) {
                 ^
crc32c/crc32c.c:92:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (size_t li = 0; li < running_length/4; li++) {
     ^
crc32c/crc32c.c:103:17: error: redefinition of ‘li’
     for (size_t li=0; li < end_bytes; li++) {
                 ^
crc32c/crc32c.c:92:17: note: previous definition of ‘li’ was here
     for (size_t li = 0; li < running_length/4; li++) {
                 ^
crc32c/crc32c.c:103:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (size_t li=0; li < end_bytes; li++) {
     ^
crc32c/crc32c.c: In function ‘crc32cSlicingBy8’:
crc32c/crc32c.c:116:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (size_t li = 0; li < initial_bytes; li++) {
     ^
crc32c/crc32c.c:124:17: error: redefinition of ‘li’
     for (size_t li = 0; li < running_length/8; li++) {
                 ^
crc32c/crc32c.c:116:17: note: previous definition of ‘li’ was here
     for (size_t li = 0; li < initial_bytes; li++) {
                 ^
crc32c/crc32c.c:124:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (size_t li = 0; li < running_length/8; li++) {
     ^
crc32c/crc32c.c:143:17: error: redefinition of ‘li’
     for (size_t li=0; li < end_bytes; li++) {
                 ^
crc32c/crc32c.c:124:17: note: previous definition of ‘li’ was here
     for (size_t li = 0; li < running_length/8; li++) {
                 ^
crc32c/crc32c.c:143:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (size_t li=0; li < end_bytes; li++) {
     ^
crc32c/crc32c.c: In function ‘crc32cHardware32’:
crc32c/crc32c.c:154:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (size_t i = 0; i < length / sizeof(uint32_t); i++) {
     ^
crc32c/crc32c.c: In function ‘crc32cHardware64’:
crc32c/crc32c.c:194:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (size_t i = 0; i < length / sizeof(uint64_t); i++) {
     ^
make: **\* [crc32c/crc32c.o] Fehler 1

**Comment by ahknight** [comment]
It tells you the problem in the output.

crc32c/crc32c.c:84:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code

Update your CFLAGS and try again. Note this was developed against LLVM/Clang which uses C(20)11 by default vs GCC's C(19)90.
